### ISSUE TITLE
The usage of the project.

### ISSUE THREAD

**Issue by Stanla** [tiirex9/telegram-savephotos#1]
Hi bro,
  I'm looking for a solution that save all photos sent in the telegram group/channel . 
  Luckily,Your project seems offered a chance. 😄 
 So,There are some sincere questions ： 
  1.What will the bot do if i installed it?
  2.How to operate it?
  3. Is it would save the all photos  sent in the telegram group/channel automatically ? 
 I'd appreciate it if you could help me. 😃

**Comment by tiirex9** [comment]
1. The bot just saves every photo it receives (from a whitelisted user or group) to the filesystem (path is specified in config.json).
2. As described in the README you check it out, (if you want, you can use virtualenv for this), you install the requirements with pip -r requirements.txt. The you need to request a bot api token from https://t.me/botfather and put it in a file called API_TOKEN. Then you can start it with `python main.py` if everything works as expected you can run it in the background.
3. Yes. I know it works for whitelisted direct chats and groups. I'm not sure if it works for channels though. I think it SHOULD work in channels. 😆 

It's really a quick and dirty implementation and is not really maintained, but if I can help you any further just write me. :)
